spring:
  config:
    activate:
      on-profile: prod

  # [PostgreSQL RDS 설정]
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # [Neo4j 설정]
  neo4j:
    uri: ${NEO4J_URI}
    authentication:
      username: ${NEO4J_USERNAME}
      password: ${NEO4J_PASSWORD}

# [FastAPI 호출 주소]
external:
  fastapi:
    url: ${FASTAPI_URL}